version: '3'

services:
  geminiprochat:
    build: .
    container_name: geminiprochat
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=YOUR_GEMINI_API_KEY
      # - HTTPS_PROXY=YOUR_HTTPS_PROXY
      - API_BASE_URL=https://65b11b2f6638ca09ef4e2784--elaborate-druid-a39b25.netlify.app/
      # - HEAD_SCRIPTS=YOUR_HEAD_SCRIPTS
      # - PUBLIC_SECRET_KEY=YOUR_SECRET_KEY
      # - SITE_PASSWORD=YOUR_SITE_PASSWORD
      # - OPENAI_API_MODEL=YOUR_OPENAI_API_MODEL

